---
title: "Computational Text Analysis"
author: "Malo Jan & Luis Sattelmayer"
format: html
date: today
bibliography: tada.bib


---

# Course outline

This course is an introduction to textual statistics, text-as-data methods and computational social sciences. Through the last decades, both methods in quantitative text analysis and the availability of text has increased throughout the field of social sciences. With increasing computational power of home computers, social scientists are now more and more able to overcome constraints of data availability and requirements of time when analyzing large corpora of text. Advances in artificial intelligence and natural language processing are increasingly being imported into the social sciences, with their advantages but also their shortcomings. \par
This class aims to introduce the students to the logic and methods behind the new turning in computational social sciences. It will gently expose students to more and more elaborated text-as-data [Malo: and Machine Learning]methods throughout the semester. The class will be divided in three sections which build on each other: 

1. Data Collection \& Construction of Corpus
2. Text-Mining and Text-Scaling
3. Supervised & Unsupervised Machine Learning

The first block on \textit{Data Collection \& Construction of Corpus} will teach students the logic of scraping and automated text collection. Further, students will be familiarized with working on Github. The second part, week 4 to 6, is supposed to show conventional methods of text mining, frequency calculations, scaling text and measuring distances between texts. The third section will introduce students to the idea of unsupervised methods such as topic models and the logic of training algorithms by hand to estimate a bigger corpus later on.[Malo : le SML consiste pas forcément à annoter des textes parce que parfois tu les as déjà les labels, je mettrais plutôt : introduce students to unsupervised and supervised machine learning techniques to analyze text]. 

# Objectives

The objectives of this class are fourfold. First, we wish to familiarize students with the logic of overcoming data shortcomings by collecting (in automated fashion) textual data and selecting the right and pertinent corpora for their research interest. Second, this class is designed to expose students to the variety of current methods available to conduct quantitative text analyses in a way that they are able to conduct their own research after this class potentially preparing them for research projects of a bigger scope using the covered methods. Third, this class puts special emphasis on reproducible and open research. Students will therefore learn how to use Github and reproducible documentation of code. The last objective is that the students will learn advanced and efficient data management techniques throughout the sessions by working with text-as-data methods allowing them to work with big databases of text or other datasets. [Malo : plutôt que data management, je mettrais : improve general programming skills and knowledge of quantitative reasoning that can be applied to deal with other data than text] \par  

[Malo : ajouter quelque chose sur le fait qu'aider les étudiants pour leur mémoire]

# Reading Policy

There is no strict reading policy and the sessions will mostly consist of the presentation of the methods by the teachers and applications in RStudio. For each session, we will try, however, to provide both methods papers as well as publications in which the presented methods are applied in order to highlight the possibilities, advantages and shortcomings of each.

# Course Validation

As emphasized in the previous paragraph, a strong focus will be put on the final project of the class. From the start, students are asked to think about a final project for this class that will have to be handed in after session 12. Students are required to choose one method covered in one of the classes and apply them to a research question. [Malo : peut être que c'est restrictif de choisir une méthode ? ] Given the course's emphasis on reproducible code, students must also hand in an annotated version of their code in Markdown format. \par

# Pre-requisites

An intermediate knowledge of RStudio is recommended. Further familiarity with Git, Markdown or Quarto is an advantage but not a must [Malo : je pense que personne est familier avec GIT ahah donc est-ce que ca vaut la peine de le mettre ? Est-ce que intermédiaire ça fait pas trop peur ahah, certaines personnes peut être à l'aise se sentent pas intermédiaire, faut pas qu'il y ait de barrière à l'entrée en termes de self-competence]. In terms of coding skills, this course picks up where the RStudio lab sessions for the Quantitative Methods II lecture ended.



\pagebreak
# Detailed Outline of the Sessions

## 1. Introduction

- What is Computational Social Science (CSS)
- What is text-as-data
- Applications of text as data methods in political science/social sciences
- Importance of reproducibility in CSS
- Introduction to and setting up GitHub

##### References

- Edelmann, A., Wolff, T., Montagne, D., & Bail, C. A. (2020). Computational social science and sociology. Annual Review of Sociology, 46, 61-81.

- Grimmer, J., & Stewart, B. M. (2013). Text as data: The promise and pitfalls of automatic content analysis methods for political texts. Political analysis, 21(3), 267-297.

- Grimmer, J., Roberts, M. E., & Stewart, B. M. (2021). Machine learning for social science: An agnostic approach. Annual Review of Political Science, 24, 395-419.

## 2. Collecting text from the web (1)

- The logic of webscraping
- Scraping ethics
- APIs
- Scraping static webpages with `rvest`
- What makes a good corpus?

##### References

- Bruns, A. (2019). After the ‘APIcalypse’: Social media platforms and their fight against critical scholarly research. Information, Communication & Society, 22(11), 1544-1566.

- Munzert, S., Rubba, C., Meißner, P., & Nyhuis, D. (2014). Automated data collection with R: A practical guide to web scraping and text mining. John Wiley & Sons.


## 3. Collecting text from the web (2)

- From research question to assembling the corpus
- Lab session on webscraping


## 4. Manipulating text

- Cleaning a corpus of texts
- String manipulation in R with `stringr`
- Pattern matching with regular expressions (RegEx)

## 5. Introduction to text-mining

- Transforming text into data
- `quanteda` \& `tm` package [Malo : surtout `tidytext`, tm c'est outdated ahah]
- Text pre-processing : tokenization, document-feature-matrix
- Word frequencies and Tf-idf

##### References

- Silge, Julia, and David Robinson. Text mining with R: A tidy approach. " O'Reilly Media, Inc.", 2017.

## 6. Scaling methods

- Measuring distances between texts
- Wordscores
- Wordfish

##### References

- Braby, D., Guinaudeau, B., & Sältzer, M. Scaling models in political science. In Elgar Encyclopedia of Technology and Politics (pp. 98-105). Edward Elgar Publishing.

- Lowe, W. (2008). Understanding wordscores. Political Analysis, 16(4), 356-371.

- Proksch, S. O., & Slapin, J. B. (2010). Position taking in European Parliament speeches. British Journal of Political Science, 40(3), 587-611.

## 7. Unsupervised learning (1) : topic models

- Overview of machine learning methods
- Topic modelling with Latent Dirichlet Allocation (LDA) and Structural Topic Modeling (STM)

#####  References

DiMaggio, P., Nag, M., & Blei, D. (2013). Exploiting affinities between topic modeling and the sociological perspective on culture: Application to newspaper coverage of US government arts funding. Poetics, 41(6), 570-606.

Finseraas, H., Høyland, B., & Søyland, M. G. (2021). Climate politics in hard times: How local economic shocks influence MPs attention to climate change. European Journal of Political Research, 60(3), 738-747.

## 8. Unsupervised learning (2) : word embeddings

- Understanding words in context
- Pre-trained word embeddings

##### References

- Rodriguez, Pedro L., and Arthur Spirling. "Word embeddings: What works, what doesn’t, and how to tell the difference for applied research." The Journal of Politics 84.1 (2022): 101-115.

- Rheault, L., & Cochrane, C. (2020). Word embeddings for the analysis of ideological placement in parliamentary corpora. Political Analysis, 28(1), 112-133.

## 9. Supervised Machine Learning (1)

- Introduction to supervised machine learning
- Use-cases of SML in political science
- Introduction  to `tidymodels` in R
- BERT [Malo : je sais pas si on va pouvoir BERT directement parce que R]

##### References

- Bonikowski, B., Luo, Y., & Stuhler, O. (2022). Politics as Usual? Measuring Populism, Nationalism, and Authoritarianism in US Presidential Campaigns (1952–2020) with Neural Language Models. Sociological Methods & Research, 51(4), 1721-1787.

- Hvitfeldt, E., & Silge, J. (2021). Supervised machine learning for text analysis in R. CRC Press.

- Kuhn, M., & Silge, J. (2022). Tidy Modeling with R. " O'Reilly Media, Inc.".

- Peterson, A., & Spirling, A. (2018). Classification accuracy as a substantive quantity of interest: Measuring polarization in westminster systems. Political Analysis, 26(1), 120-128.

## 10. Supervised Machine Learning (2)

- Labelling text 
- Active learning
- Lab session

#### References

- Do, Salomé, Étienne Ollion, and Rubing Shen. "The Augmented Social Scientist: Using Sequential Transfer Learning to Annotate Millions of Texts with Human-Level Accuracy." Sociological Methods & Research (2022): 00491241221134526.

- Miller, B., Linder, F., & Mebane, W. R. (2020). Active learning approaches for labeling text: review and assessment of the performance of active learning approaches. Political Analysis, 28(4), 532-551.


## 11. Supervised Machine Learning (3)

- Deep-learning, transformers, languages models and transfer learning
- Lab session


## 12. Conclusion

- Recent developments in computational text analysis
- Ideally students will present their final papers here

#### References

- Baden, C., Pipal, C., Schoonvelde, M., & van der Velden, M. A. G. (2022). Three gaps in computational text analysis methods for social sciences: A research agenda. Communication Methods and Measures, 16(1), 1-18.

- Licht, H. (2022). Cross-Lingual Classification of Political Texts Using Multilingual Sentence Embeddings. Political Analysis, 1-14.

# General references

Boehmke, B., & Greenwell, B. M. (2019). Hands-on machine learning with R. CRC press.

Gandrud, C. (2013). Reproducible research with R and R studio. CRC Press.

Grimmer, J., Roberts, M. E., & Stewart, B. M. (2022). Text as data: A new framework for machine learning and the social sciences. Princeton University Press.

Hvitfeldt, E., & Silge, J. (2021). Supervised machine learning for text analysis in R. CRC Press.

Kuhn, M., & Silge, J. (2022). Tidy Modeling with R. " O'Reilly Media, Inc.".

Salganik, M. J. (2019). Bit by bit: Social research in the digital age. Princeton University Press.

Silge, J., & Robinson, D. (2017). Text mining with R: A tidy approach. " O'Reilly Media, Inc.".


