---
title : "Introduction to Computational Social Sciences"
author : "Malo Jan & Luis Sattelmayer"
date : today
css: styles.css  # Link to your custom CSS file
execute: 
  echo: false
  warning: false
format: 
    revealjs:
        highlight-style: breeze
        theme: simple
        pdf-separate-fragments: false
        self-contained: true
editor_options: 
  chunk_output_type: console
---

## Introduction to CSS {.smaller}

- Introduce to the field of CSS
- Mostly about text analysis
- Only the basics to explore more
- Require you know about programming
- Goal to provide less technical introduction possible, focus on use cases

## 

- Rise of digital text data
- IA

## CSS pipeline

# New developments

- Muiltilingual text analysis
- Image, Video as data, multimodal analysis
- Generative language
- One particular feature of text data : it is unstructured and not produced by researchers

# Corpus selection

## What is a corpus ? {.smaller}

- Every project involving text analysis starts with a corpus
- Choose documents to analyze
- A corpus is a collection of texts
- Crucial task and often overlooked
- Corresponds to identifying the population of interest

## Corpus selection {.smaller}

- Start a research interest about a social phenomena
- What would be a corpus that would help me answer this question ?
- Eg. twitter data is fun but not useful for everything
- Corpus and metadata

##

- How exhaustive is the corpus ? Is it only a sample or not
- Think about data generation process : how these texts were produced
- Important to explore, read some of the texts
- Think about quantity of interest : what could you derive as a measure from those texts : eg. How much a given topic is discussed in these texts


## Finding or creating a corpus {.smaller}

-  Existing corpora vs creating original corpora
- Existing corpora : 
    - Texs datasets already available in such format : eg. Manifesto corpus, UNGA corpus, corpus that other researchers have collected, Open data 
- Collecting texts
    - API
    - Web scraping
    
## API {.smaller}


- Apycalipse : Facebook, Instagram and Twitter Researcher access have closed (see [minet](https://github.com/medialab/minet) for workaround)
- [Bluesky](https://github.com/JBGruber/atrrr)
